### ISSUE TITLE
Image Slider

### ISSUE THREAD

**Issue by willis-meyers** [willis-meyers/artgallery#6]
@SofyaMulenok @koreoliver -
Hey folks,
I deployed our site to aggregatespace.com/hackbright so we can start viewing mobile and windows bugs more easily. I am testing out a new slider since the bootstrap carousel wasn't really working for me aesthetically. Checkout the link above on https://www.browserstack.com/responsive and we can get going from there. Looking forward to tonight!

**Comment by SofyaMulenok** [comment]
@willis-meyers I like it that way! I'm excited, this is coming together nicely.
Awesome job on the contact page, too!

**Comment by koreoliver** [comment]
awesome! it's looking good!
